# Generated by Django 4.0.1 on 2022-03-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_membre', models.CharField(max_length=50)),
                ('prenom_membre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pv', models.CharField(max_length=80)),
                ('but_pv', models.TextField(blank=True, null=True)),
                ('point_abordes_pv', models.TextField(blank=True, null=True)),
                ('decision_prise_pv', models.TextField(blank=True, null=True)),
                ('date_pv', models.DateField()),
                ('h_debut_pv', models.TimeField()),
                ('h_fin_pv', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=100)),
                ('description_tache', models.TextField(blank=True, null=True)),
                ('PV', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pv')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='membre',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tache'),
        ),
    ]
