# Generated by Django 4.0.1 on 2022-03-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_membre_pv_tache_delete_item_membre_tache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pv',
            options={'ordering': ['-date_pv']},
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='PV',
            new_name='PV_att',
        ),
    ]
