# Generated by Django 4.0.1 on 2022-03-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pv_options_rename_pv_tache_pv_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='pv_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pv'),
        ),
    ]
